<?php

// this file is automatically generated by kickass-libexec scripts...

// you can change the name but not the code...
define( 'MUDBALL_NAME', 'Mudball: Web Framework and Toolkit for PHP' );
define( 'MUDBALL_CODE', 'mudball' );

//define( 'MUDBALL_VERSION', '0.5.1721' );
define( 'MUDBALL_VERSION_MAJOR', 0 );
define( 'MUDBALL_VERSION_MINOR', 5 );
define( 'MUDBALL_VERSION_PATCH', 1721 );

define(
  'MUDBALL_SVN_DATE',
  '$Date: 2024-09-12 01:29:26 +1000 (Thu, 12 Sep 2024) $'
);
define( 'MUDBALL_SVN_REVISION', '$Revision: 234728203 $' );
define( 'MUDBALL_SVN_AUTHOR', '$Author: jj5 $' );

define( 'MUDBALL_GIT_DATE', '2024-09-12 01:29:26 +1000 (Thu, 12 Sep 2024)' );
